spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ka1ach260
    url: jdbc:postgresql://localhost:5432/school_diary
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update

